document.write("	<div class='col-lg-2 hidden-sm hidden-xs' style='background:url(img/bg2a.jpg);' >	");
document.write("		<ul class='list-group leftmenuword'>	");
document.write("		  <li class='list-group-item list-group-item-info " + (varleft==0?"active":"") + "'><a href='aboutyoga.htm'>瑜伽好處</a></li>	");
document.write("		  <li class='list-group-item list-group-item-info " + (varleft==1?"active":"") + "'><a href='aboutyoga.htm#space'>瑜伽意境</a></li>	");
document.write("		  <li class='list-group-item list-group-item-info " + (varleft==2?"active":"") + "'><a href='aboutyoga2.htm'>Windy 小叮嚀</a></li>	");
document.write("		  <li class='list-group-item list-group-item-info " + (varleft==3?"active":"") + "'><a href='aboutyoga3.htm'>健康新知</a></li>	");
document.write("		  <li class='list-group-item list-group-item-info " + (varleft==4?"active":"") + "'><a href='aboutyoga4.htm'>眼球運動</a></li>	");
document.write("		</ul>				");
document.write("	</div>	");
document.write("	<div class='dropdown hidden-lg hidden-md col-sm-12 col-xs-12'style='padding:0px;'>	");
document.write("		<button class='btn btn-warning dropdown-toggle' type='button' data-toggle='dropdown' style='background:#952b2b;width:100%'>關於瑜珈");
document.write("			<span class='caret'></span>	");
document.write("		</button>	");
document.write("		<ul class='dropdown-menu' style='width:100%'>	");
document.write("		  <li><a href='aboutyoga.htm'>瑜伽好處</a></li>	");
document.write("		  <li><a href='aboutyoga.htm#space'>瑜伽意境</a></li>	");
document.write("		  <li><a href='aboutyoga2.htm'>Windy 小叮嚀</a></li>	");
document.write("		  <li><a href='aboutyoga3.htm'>健康新知</a></li>	");
document.write("		  <li><a href='aboutyoga4.htm'>眼球運動</a></li>	");
document.write("		</ul>");
document.write("	 </div>		");
