document.write("	<div class='col-lg-2 hidden-sm hidden-xs' style='background:url(img/bg4a.jpg);' >	");
document.write("		<ul class='list-group leftmenuword'>	");
document.write("		  <li class='list-group-item list-group-item-info " + (varleft==0?"active":"") + "'><a href='air_teacher.htm'>Coco老師</a></li>	");
document.write("		  <li class='list-group-item list-group-item-info " + (varleft==1?"active":"") + "'><a href='air_teacher2.htm#space'>小可老師</a></li>	");
document.write("		  <li class='list-group-item list-group-item-info " + (varleft==2?"active":"") + "'><a href='air_teacher3.htm'>橘子老師</a></li>	");
document.write("		  <li class='list-group-item list-group-item-info " + (varleft==3?"active":"") + "'><a href='air_teacher4.htm'>Catherine老師</a></li>	");
document.write("		  <li class='list-group-item list-group-item-info " + (varleft==4?"active":"") + "'><a href='air_teacher5.htm'>Fei老師</a></li>	");
document.write("		</ul>				");
document.write("	</div>	");
document.write("	<div class='dropdown hidden-lg hidden-md col-sm-12 col-xs-12'style='padding:0px;'>	");
document.write("		<button class='btn btn-info dropdown-toggle' type='button' data-toggle='dropdown' style='background:#2b957c;width:100%'>空中瑜珈");
document.write("			<span class='caret'></span>	");
document.write("		</button>	");
document.write("		<ul class='dropdown-menu' style='width:100%'>	");
document.write("		  <li><a href='air_teacher.htm'>Coco老師</a></li>	");
document.write("		  <li><a href='air_teacher2.htm#space'>小可老師</a></li>	");
document.write("		  <li><a href='air_teacher3.htm'>橘子老師</a></li>	");
document.write("		  <li><a href='air_teacher4.htm'>Catherine老師</a></li>	");
document.write("		  <li><a href='air_teacher5.htm'>Fei老師</a></li>	");
document.write("		</ul>");
document.write("	 </div>		");
