document.write("	<div class='col-lg-2 hidden-sm hidden-xs' style='background:url(img/bg7a.jpg);' >	");
document.write("		<ul class='list-group leftmenuword'>	");
document.write("		  <li class='list-group-item list-group-item-info " + (varleft==0?"active":"") + "'><a href='teacher.htm'>華云老師</a></li>	");
document.write("		  <li class='list-group-item list-group-item-info " + (varleft==1?"active":"") + "'><a href='teacher7_shi.htm'>英玲老師</a></li>	");
document.write("		  <li class='list-group-item list-group-item-info " + (varleft==2?"active":"") + "'><a href='teacher9.htm'>瑞雲老師</a></li>	");
document.write("		  <li class='list-group-item list-group-item-info " + (varleft==3?"active":"") + "'><a href='teacher10.htm'>祖威老師</a></li>	");
document.write("		  <li class='list-group-item list-group-item-info " + (varleft==4?"active":"") + "'><a href='teacher11.htm'>芬芬老師</a></li>	");
document.write("		  <li class='list-group-item list-group-item-info " + (varleft==5?"active":"") + "'><a href='teacher12.htm'>Coco老師</a></li>	");
document.write("		  <li class='list-group-item list-group-item-info " + (varleft==6?"active":"") + "'><a href='teacher13.htm'>Joy老師</a></li>	");
document.write("		</ul>				");
document.write("	</div>	");
document.write("	<div class='dropdown hidden-lg hidden-md col-sm-12 col-xs-12'style='padding:0px;'>	");
document.write("		<button class='btn btn-primary dropdown-toggle' type='button' data-toggle='dropdown' style='background:#95522b;width:100%;font-size:1.1em !important;'>老師	");
document.write("			<span class='caret'></span>	");
document.write("		</button>	");
document.write("		<ul class='dropdown-menu' style='width:100%;font-size:1.1em !important;'>	");
document.write("		  <li><a href='teacher.htm'>華云老師</a></li>	");
document.write("		  <li><a href='teacher7_shi.htm'>英玲老師</a></li>	");
document.write("		  <li><a href='teacher9.htm'>瑞雲老師</a></li>	");
document.write("		  <li><a href='teacher10.htm'>祖威老師</a></li>	");
document.write("		  <li><a href='teacher11.htm'>芬芬老師</a></li>	");
document.write("		  <li><a href='teacher12.htm'>Coco老師</a></li>	");
document.write("		  <li><a href='teacher13.htm'>Joy老師</a></li>	");
document.write("		</ul>");
document.write("	 </div>		");
