var dt1=new Date();
document.write("  <nav class='navbar navbar-default navbar-fixed-top'  style='background-color: #BB3800 !important;border-color:#BB3800;background-image: linear-gradient(to right, #BB3800 , #992f0b );'>");
document.write("      <div class='navbar-header'> ");
 document.write("        <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#navbar' aria-expanded='false' aria-controls='navbar'> ");
 document.write("          <span class='sr-only'>Toggle navigation</span> ");
 document.write("          <span class='icon-bar'></span> ");
 document.write("          <span class='icon-bar'></span> ");
 document.write("          <span class='icon-bar'></span> ");
 document.write("        </button> ");
 document.write("        <a class='tophide navbar-brand' href='#' style='color:#fff;font-size:22px;'>華云瑜珈</a> ");
 document.write("      </div> ");
document.write("<div id='navbar' class='navbar-collapse collapse'>"); 
document.write("<table  width='90%' border='0' cellspacing='0' cellpadding='0' style='margin-bottom: 10px;'> ");
document.write("	<tr> ");
document.write("		<td class='toplogo'><img src='img/top1.jpg' border=0 width=></img></td> ");
//document.write("		<td align='right' style='padding-top:48px;padding-right:20px;color:#fff;font-size:14px;'>中華民國 " + (dt1.getFullYear()-1911) + " 年 " + (dt1.getMonth()+1) + " 月 " + (dt1.getDate()) + " 日</td> ");
//document.write("	</tr> ");
//document.write("	<tr> ");
document.write("		<td style='height:23px;background-color:#BB3800;background-image: linear-gradient(to right, #BB3800 , #992f0b );    vertical-align: bottom;'> ");
document.write("			<ul class='cbdb-menu' style='margin-top:0px;bgcolor=#BB3800'> ");
document.write("			  <li><a href='index.html' class='red topmenu menutext' id=top1>關於華云</a> </li> ");
document.write("			  <li><a href='aboutyoga.htm' class='red topmenu' id=top2>關於瑜珈</a> </li> ");
document.write("			  <li><a href='trx_teacher2.htm' class='red topmenu' id=top3>TRX教練</a> </li> ");
document.write("			  <li><a href='teacher.htm' class='red topmenu' id=top4>地板瑜珈</a> </li> ");
document.write("			  <li><a href='air_teacher.htm' class='red topmenu' id=top5>空中瑜珈</a> </li> ");
document.write("			  <li><a href='schedule.htm' class='red topmenu' id=top6>授課時間</a> </li> ");
document.write("			  <li><a href='contact.htm' class='red topmenu' id=top7>聯絡方式</a> </li> ");
document.write("			  <li ><a href='https://www.facebook.com/windyoga' class='red topmenu' id=top8 target=_blank><image src=img/icon_fb.png  style='width: 15px;margin-right: 5px;vertical-align: middle;'>FB</a> </li> ");
document.write("			  <li ><a href='https://www.instagram.com/reel/C0EX3AVRJXU/?igshid=NjZiM2M3MzIxNA==' class='red topmenu' id=top8 target=_blank><image src=img/icon_ig.png style='width: 15px;margin-right: 5px;vertical-align: middle;'>IG</a> </li> ");
document.write("			</ul> ");
document.write("		</td> ");
document.write("	</tr> ");
document.write("	</table></nav> ");
document.write("	<div> ");
document.write("<table class='contentshow' border='0' cellspacing='0' cellpadding='0' style='background-color: " + topbackcolor + " !important;'> ");
document.write("	<tr> ");
document.write("		<td colspan=2 style='background-color:#BB3800'> ");
document.write("				<img src='img/top1.png' border=0  style='display:none;width:100%;' id='top1img'></img> ");
document.write("				<img src='img/top2.png' border=0  style='display:none;width:100%;' id='top2img'></img> ");
document.write("				<img src='img/top3.png' border=0  style='display:none;width:100%;' id='top3img'></img> ");
document.write("				<img src='img/top4.png' border=0  style='display:none;width:100%;' id='top4img'></img> ");
document.write("				<img src='img/top5.png' border=0  style='display:none;width:100%;' id='top5img'></img> ");
document.write("				<img src='img/top6.png' border=0  style='display:none;width:100%;' id='top6img'></img> ");
document.write("				<img src='img/top7.png' border=0  style='display:none;width:100%;' id='top7img'></img> ");
document.write("				<img src='img/top8.png' border=0  style='display:none;width:100%;' id='top8img'></img> ");
document.write("		</td> ");
document.write("	</tr> ");
document.write("</table> ");
document.write("</div> ");