document.write("	<div class='col-lg-2 hidden-sm hidden-xs' style='background:url(img/bg7a.jpg);' >	");
document.write("		<ul class='list-group leftmenuword'>	");
document.write("		  <li class='list-group-item list-group-item-info " + (varleft==0?"active":"") + "'><a href='trx_teacher2.htm'>Leo教練</a></li>	");
document.write("		  <li class='list-group-item list-group-item-info " + (varleft==1?"active":"") + "'><a href='trx_teacher.htm'>光光教練</a></li>	");
document.write("		</ul>				");
document.write("	</div>	");
document.write("	<div class='dropdown hidden-lg hidden-md col-sm-12 col-xs-12'style='padding:0px;'>	");
document.write("		<button class='btn btn-danger dropdown-toggle' type='button' data-toggle='dropdown' style='background:#7c3477;width:100%;font-size:1.1em !important;'>教練	");
document.write("			<span class='caret'></span>	");
document.write("		</button>	");
document.write("		<ul class='dropdown-menu' style='width:100%;font-size:1.1em !important;'>	");
document.write("			<li><a href='trx_teacher2.htm'>Leo教練</a></li>	");
document.write("			<li><a href='trx_teacher.htm'>光光教練</a></li>	");
document.write("		</ul>");
document.write("	 </div>		");
