var dt1=new Date();
document.write("<table  width='770' border='0' cellspacing='0' cellpadding='0' bgcolor='" + topbackcolor + "'> ");
document.write("	<tr> ");
document.write("		<td><img src='i/" + topwhat + ".jpg' border=0 width=></img></td> ");
document.write("		<td align='right' style='padding-top:48px;padding-right:20px;font-size:12px;color:#000'>中華民國 " + (dt1.getFullYear()-1911) + " 年 " + (dt1.getMonth()+1) + " 月 " + (dt1.getDate()) + " 日</td> ");
document.write("	</tr> ");
document.write("	<tr> ");
document.write("		<td colspan=2 align='left' style='height:10px;background-color:#BB3800'> ");
document.write("			<ul class='cbdb-menu' style='margin-left:-40px;margin-top:0px;bgcolor=#BB3800'> ");
document.write("			  <li><a href='aboutwind.htm' class='red topmenu' id=top1>關於華云</a> </li> ");
document.write("			  <li><a href='aboutyoga.htm' class='red topmenu' id=top2>關於瑜珈</a> </li> ");
document.write("			  <li><a href='qualification.htm' class='red topmenu' id=top3>教學環境</a> </li> ");
document.write("			  <li><a href='teacher.htm' class='red topmenu' id=top4>師資介紹</a> </li> ");
document.write("			  <li><a href='successful.htm' class='red topmenu' id=top5>學員分享</a> </li> ");
document.write("			  <li><a href='schedule.htm' class='red topmenu' id=top6>授課時間</a> </li> ");
document.write("			  <li><a href='contact.htm' class='red topmenu' id=top7>聯絡方式</a> </li> ");
document.write("			  <li ><a href='https://www.facebook.com/windyoga' class='red topmenu' id=top8>Facebook</a> </li> ");
document.write("			</ul> ");
document.write("		</td> ");
document.write("	</tr> ");
document.write("	<tr> ");
document.write("		<td colspan=2 style='height:124px;background-color:#BB3800'> ");
document.write("			<div id=topimg style='position:relative;top:-60px;left:0px;'> ");
document.write("				<div style='position:absolute;top:0px;left:0px;display:none' id='top1img'><img src='i/top1.png' border=0></img></div> ");
document.write("				<div style='position:absolute;top:0px;left:0px;display:none' id='top2img'><img src='i/top2.png' border=0></img></div> ");
document.write("				<div style='position:absolute;top:0px;left:0px;display:none' id='top3img'><img src='i/top3.png' border=0></img></div> ");
document.write("				<div style='position:absolute;top:0px;left:0px;display:none' id='top4img'><img src='i/top4.png' border=0></img></div> ");
document.write("				<div style='position:absolute;top:0px;left:0px;display:none' id='top5img'><img src='i/top5.png' border=0></img></div> ");
document.write("				<div style='position:absolute;top:0px;left:0px;display:none' id='top6img'><img src='i/top6.png' border=0></img></div> ");
document.write("				<div style='position:absolute;top:0px;left:0px;display:none' id='top7img'><img src='i/top7.png' border=0></img></div> ");
document.write("				<div style='position:absolute;top:0px;left:0px;display:none' id='top8img'><img src='i/top8.png' border=0></img></div> ");
document.write("			</div> ");
document.write("		</td> ");
document.write("	</tr> ");
document.write("</table> ");